services:
  youtube-downloader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - .:/app
    restart: always